package vistas;

import com.mycompany.main.Rutina;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.JFrame;

public class menuServicios extends javax.swing.JFrame {
    
    Rutina r;
    JFrame menuPrincipal;

    public menuServicios(JFrame menuPrincipal, Rutina rutina) {
        this.menuPrincipal = menuPrincipal;
        this.r = rutina;
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Menu Principal");
        
        addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                menuPrincipal.setVisible(true);
                dispose();
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnAgregarServicios = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        btnEditarServicios = new javax.swing.JButton();
        btnInactivarServicios = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        jLabel1.setText("MultiClean");

        btnAgregarServicios.setText("Agregar Servicios");
        btnAgregarServicios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarServiciosActionPerformed(evt);
            }
        });

        jLabel3.setText("Menú de Servicios");

        btnEditarServicios.setText("Editar Servicios");
        btnEditarServicios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarServiciosActionPerformed(evt);
            }
        });

        btnInactivarServicios.setText("Inactivar Servicios");
        btnInactivarServicios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInactivarServiciosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnInactivarServicios)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(6, 6, 6)
                            .addComponent(btnEditarServicios))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(33, 33, 33)
                            .addComponent(jLabel1))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(10, 10, 10)
                            .addComponent(jLabel3))
                        .addComponent(btnAgregarServicios)))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(5, 5, 5)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAgregarServicios)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEditarServicios)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnInactivarServicios)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarServiciosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarServiciosActionPerformed
        agregarServicios as = new agregarServicios(menuPrincipal, r);
        as.setVisible(true);
    }//GEN-LAST:event_btnAgregarServiciosActionPerformed

    private void btnEditarServiciosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarServiciosActionPerformed
        editarServicios es = new editarServicios(menuPrincipal, r);
        es.setVisible(true);
    }//GEN-LAST:event_btnEditarServiciosActionPerformed

    private void btnInactivarServiciosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInactivarServiciosActionPerformed
        inactivarServicios es = new inactivarServicios(menuPrincipal, r);
        es.setVisible(true);
    }//GEN-LAST:event_btnInactivarServiciosActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarServicios;
    private javax.swing.JButton btnEditarServicios;
    private javax.swing.JButton btnInactivarServicios;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
